from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

class SysVarNotFoundError(Exception):
    var_key: str
    var_type: str
    var_path: str
    def __init__(self, *args: object, **kwargs: Dict[str, str]) -> None: ...

def get(key: str, *, default: Optional[Any] = ..., **kwargs: Dict[str, str]) -> str: ...
def get_bool(key: str, **kwargs: Dict[str, Any]) -> bool: ...
def get_datetime(key: str, **kwargs: Dict[str, Any]) -> datetime: ...
def get_float(key: str, **kwargs: Dict[str, Any]) -> float: ...
def get_int(key: str, **kwargs: Dict[str, Any]) -> int: ...
def get_json(key: str, **kwargs: Dict[str, Any]) -> Union[Dict[str, Any], List[Any]]: ...
def get_path(key: str, **kwargs: Dict[str, Any]) -> Path: ...
