from datetime import datetime
from pathlib import Path
from typing import Any

__all__ = ['SysVarNotFoundError', 'get', 'get_bool', 'get_datetime', 'get_float', 'get_int', 'get_json', 'get_path']

class SysVarNotFoundError(Exception):
    var_key: str
    var_type: str
    var_path: str
    def __init__(self, *args: object, **kwargs: dict[str, str]) -> None: ...

def get(key: str, /, *, default: Any | None = None, __var_type: str = 'str') -> str: ...
def get_bool(key: str, /, *, default: Any | None = None) -> bool: ...
def get_datetime(key: str, /, *, default: Any | None = None) -> datetime: ...
def get_float(key: str, /, *, default: Any | None = None) -> float: ...
def get_int(key: str, /, *, default: Any | None = None) -> int: ...
def get_json(key: str, /, *, default: Any | None = None) -> dict[str, Any] | list[Any]: ...
def get_path(key: str, /, *, default: Any | None = None) -> Path: ...
